import React from "react";
import {
  AcUnitIcon,
  CloudIcon,
  DarkModeIcon,
  FormatAlignCenterIcon,
  ThunderstormIcon,
  WaterDropIcon,
  WbSunnyIcon,
} from "../components/Icons";

export enum WeatherIcons {
  ClearSkyDay = "01d",
  ClearSkyNight = "01n",
  FewCloudsDay = "02d",
  FewCloudsNight = "02n",
  ScatteredCloudsDay = "03d",
  ScatteredCloudsNight = "03n",
  BrokenCloudsDay = "04d",
  BrokenCloudsNight = "04n",
  ShowerRainDay = "09d",
  ShowerRainNight = "09n",
  RainDay = "10d",
  RainNight = "10n",
  ThunderstormDay = "11d",
  ThunderstormNight = "11n",
  SnowDay = "13d",
  SnowNight = "13n",
  MistDay = "50d",
  MistNight = "50n",
}

export const weatherIcons: Record<WeatherIcons, React.ReactElement<React.ReactSVG>> = {
  [WeatherIcons.ClearSkyDay]: <WbSunnyIcon sx={{ height: 60, width: 60 }}/>,
  [WeatherIcons.ClearSkyNight]: <DarkModeIcon sx={{ height: 60, width: 60 }}/>,
  [WeatherIcons.FewCloudsDay]: <CloudIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.FewCloudsNight]: <CloudIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ScatteredCloudsDay]: <CloudIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ScatteredCloudsNight]: <CloudIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.BrokenCloudsDay]: <CloudIcon sx={{ height: 60, width: 60, color: 'gray'}} />,
  [WeatherIcons.BrokenCloudsNight]: <CloudIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ShowerRainDay]: <WaterDropIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ShowerRainNight]: <WaterDropIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.RainDay]: <WaterDropIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.RainNight]: <WaterDropIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ThunderstormDay]: <ThunderstormIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.ThunderstormNight]: <ThunderstormIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.SnowDay]: <AcUnitIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.SnowNight]: <AcUnitIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.MistDay]: <FormatAlignCenterIcon sx={{ height: 60, width: 60 }} />,
  [WeatherIcons.MistNight]: <FormatAlignCenterIcon sx={{ height: 60, width: 60 }} />,
}